#!/usr/bin/env bash

export MODULES="base(00.drehbert_common,01.drehbert_app,02.drehbert_dev)"
export BASE_RELEASE_IMG_NAME=drehbert-pi-dev-os.img
export BASE_RELEASE_ZIP_NAME=drehbert-pi-dev-os.img.zip
