# led pins
GPIO_LED_GENERAL = 1
GPIO_LED_BLUETOOTH = 7
GPIO_LED_TURNTABLE = 8
GPIO_LED_ERROR = 25

# motor pins
GPIO_MOTOR_STEP = 20
GPIO_MOTOR_DIR = 16
GPIO_MOTOR_ENABLE = 21

# button pins
GPIO_BUTTON_TURNTABLE = 24
GPIO_BUTTON_BLUETOOTH = 23
